### ISSUE TITLE
Wrong configuration of fhi_caps

### ISSUE THREAD

**Issue by kele14x** [Xilinx/wireless-xorif#1]
Hi,

Seems that

https://github.com/Xilinx/wireless-xorif/blob/1ac5d7d300e8b06dc08304fdd83da8e87a32e5d4/src/libxorif/xorif_fh_func.c#L1313

should be 

`fhi_caps.iq_comp_bfp_widths = 0x5200); // 9, 12, 14`

since we are configuration UL.

**Comment by sjd-xlnx** [comment]
Code has changed, and this no longer exists.
